import {
  Code,
  DollarSign,
  GraduationCap,
  Megaphone,
  ShoppingCart,
  Stethoscope,
} from 'lucide-react';

export const industriesData = {
  technology: {
    label: 'Technology',
    icon: Code,
    skills: [
      'JavaScript',
      'TypeScript',
      'React',
      'Node.js',
      'Python',
      'Java',
      'C++',
      'Go',
      'Docker',
      'Kubernetes',
      'AWS',
      'Azure',
      'GCP',
      'MongoDB',
      'PostgreSQL',
      'Redis',
      'GraphQL',
      'REST APIs',
      'Microservices',
      'DevOps',
      'CI/CD',
      'Git',
      'Agile',
      'Scrum',
    ],
    questionTypes: [
      {
        value: 'technical-coding',
        label: 'Coding & Algorithms',
        description: 'Programming challenges and problem-solving',
        defaultQuestions: 5,
      },
      {
        value: 'technical-system',
        label: 'System Design',
        description: 'Architecture and scalability questions',
        defaultQuestions: 3,
      },
      {
        value: 'technical-tools',
        label: 'Tools & Technologies',
        description: 'Framework and technology-specific questions',
        defaultQuestions: 4,
      },
      {
        value: 'behavioral',
        label: 'Behavioral',
        description: 'Teamwork and problem-solving scenarios',
        defaultQuestions: 3,
      },
      {
        value: 'experience',
        label: 'Experience-based',
        description: 'Past project and achievement questions',
        defaultQuestions: 2,
      },
    ],
  },
  healthcare: {
    label: 'Healthcare',
    icon: Stethoscope,
    skills: [
      'Patient Care',
      'Medical Diagnosis',
      'Clinical Research',
      'Healthcare Management',
      'Medical Equipment',
      'Electronic Health Records',
      'HIPAA Compliance',
      'CPR',
      'First Aid',
      'Pharmacology',
      'Medical Terminology',
      'Healthcare Analytics',
      'Telemedicine',
      'Medical Coding',
      'Quality Assurance',
      'Risk Management',
    ],
    questionTypes: [
      {
        value: 'clinical',
        label: 'Clinical Knowledge',
        description: 'Medical procedures and patient care',
        defaultQuestions: 6,
      },
      {
        value: 'regulatory',
        label: 'Regulatory & Compliance',
        description: 'Healthcare regulations and standards',
        defaultQuestions: 3,
      },
      {
        value: 'patient-care',
        label: 'Patient Care',
        description: 'Patient interaction and care scenarios',
        defaultQuestions: 4,
      },
      {
        value: 'behavioral',
        label: 'Behavioral',
        description: 'Teamwork and ethical scenarios',
        defaultQuestions: 3,
      },
      {
        value: 'emergency',
        label: 'Emergency Response',
        description: 'Crisis management and quick decision-making',
        defaultQuestions: 2,
      },
    ],
  },
  finance: {
    label: 'Finance',
    icon: DollarSign,
    skills: [
      'Financial Analysis',
      'Risk Management',
      'Investment Banking',
      'Portfolio Management',
      'Financial Modeling',
      'Excel',
      'Bloomberg Terminal',
      'SQL',
      'Python',
      'R',
      'Regulatory Compliance',
      'Accounting',
      'Auditing',
      'Tax Planning',
      'Derivatives',
      'Fixed Income',
      'Equity Research',
      'Credit Analysis',
      'Financial Planning',
    ],
    questionTypes: [
      {
        value: 'analytical',
        label: 'Financial Analysis',
        description: 'Market analysis and financial modeling',
        defaultQuestions: 5,
      },
      {
        value: 'regulatory',
        label: 'Regulatory & Compliance',
        description: 'Financial regulations and risk management',
        defaultQuestions: 3,
      },
      {
        value: 'market-knowledge',
        label: 'Market Knowledge',
        description: 'Industry trends and market dynamics',
        defaultQuestions: 4,
      },
      {
        value: 'behavioral',
        label: 'Behavioral',
        description: 'Client relationship and decision-making',
        defaultQuestions: 3,
      },
      {
        value: 'quantitative',
        label: 'Quantitative Skills',
        description: 'Mathematical and statistical problem-solving',
        defaultQuestions: 3,
      },
    ],
  },
  education: {
    label: 'Education',
    icon: GraduationCap,
    skills: [
      'Curriculum Development',
      'Lesson Planning',
      'Classroom Management',
      'Educational Technology',
      'Student Assessment',
      'Learning Management Systems',
      'Special Education',
      'ESL Teaching',
      'Educational Psychology',
      'Differentiated Instruction',
      'Parent Communication',
      'Professional Development',
      'Educational Research',
      'Data Analysis',
      'Mentoring',
    ],
    questionTypes: [
      {
        value: 'pedagogical',
        label: 'Teaching Methods',
        description: 'Educational strategies and lesson planning',
        defaultQuestions: 5,
      },
      {
        value: 'curriculum',
        label: 'Curriculum Design',
        description: 'Course development and learning objectives',
        defaultQuestions: 3,
      },
      {
        value: 'classroom-management',
        label: 'Classroom Management',
        description: 'Student engagement and discipline',
        defaultQuestions: 4,
      },
      {
        value: 'behavioral',
        label: 'Behavioral',
        description: 'Student interaction and conflict resolution',
        defaultQuestions: 3,
      },
      {
        value: 'assessment',
        label: 'Assessment & Evaluation',
        description: 'Student evaluation and feedback methods',
        defaultQuestions: 3,
      },
    ],
  },
  marketing: {
    label: 'Marketing',
    icon: Megaphone,
    skills: [
      'Digital Marketing',
      'Social Media Marketing',
      'Content Marketing',
      'SEO',
      'SEM',
      'Google Analytics',
      'Facebook Ads',
      'Email Marketing',
      'Brand Management',
      'Market Research',
      'Campaign Management',
      'CRM',
      'Marketing Automation',
      'Graphic Design',
      'Copywriting',
      'Video Marketing',
      'Influencer Marketing',
    ],
    questionTypes: [
      {
        value: 'strategic',
        label: 'Marketing Strategy',
        description: 'Campaign planning and market positioning',
        defaultQuestions: 4,
      },
      {
        value: 'digital',
        label: 'Digital Marketing',
        description: 'Online marketing and social media strategies',
        defaultQuestions: 5,
      },
      {
        value: 'analytics',
        label: 'Analytics & Data',
        description: 'Marketing metrics and performance analysis',
        defaultQuestions: 3,
      },
      {
        value: 'behavioral',
        label: 'Behavioral',
        description: 'Creativity and client relationship scenarios',
        defaultQuestions: 3,
      },
      {
        value: 'creative',
        label: 'Creative Thinking',
        description: 'Innovation and campaign ideation',
        defaultQuestions: 3,
      },
    ],
  },
  sales: {
    label: 'Sales',
    icon: ShoppingCart,
    skills: [
      'Sales Strategy',
      'Lead Generation',
      'CRM',
      'Salesforce',
      'Cold Calling',
      'Negotiation',
      'Account Management',
      'B2B Sales',
      'B2C Sales',
      'Sales Analytics',
      'Pipeline Management',
      'Customer Relationship Management',
      'Presentation Skills',
      'Market Analysis',
      'Product Knowledge',
      'Sales Forecasting',
    ],
    questionTypes: [
      {
        value: 'sales-strategy',
        label: 'Sales Strategy',
        description: 'Sales planning and territory management',
        defaultQuestions: 4,
      },
      {
        value: 'customer-relations',
        label: 'Customer Relations',
        description: 'Client interaction and relationship building',
        defaultQuestions: 5,
      },
      {
        value: 'negotiation',
        label: 'Negotiation Skills',
        description: 'Deal closing and objection handling',
        defaultQuestions: 4,
      },
      {
        value: 'behavioral',
        label: 'Behavioral',
        description: 'Motivation and team collaboration',
        defaultQuestions: 3,
      },
      {
        value: 'product-knowledge',
        label: 'Product Knowledge',
        description: 'Understanding of products and services',
        defaultQuestions: 2,
      },
    ],
  },
};

export const mockOrganizations = [
  { id: 'org_1', name: 'TechCorp Inc.', industry: 'technology' },
  { id: 'org_2', name: 'HealthCare Solutions', industry: 'healthcare' },
  { id: 'org_3', name: 'Financial Partners', industry: 'finance' },
  { id: 'org_4', name: 'EduTech Academy', industry: 'education' },
  { id: 'org_5', name: 'Marketing Masters', industry: 'marketing' },
  { id: 'org_6', name: 'Sales Force Pro', industry: 'sales' },
];
